// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB14spd0k5x_4m6zZYWJAZLqBnI6jeZyBc',
    appId: '1:378281753444:web:c8861d508700ad29819871',
    messagingSenderId: '378281753444',
    projectId: 'automacao-5843f',
    authDomain: 'automacao-5843f.firebaseapp.com',
    storageBucket: 'automacao-5843f.firebasestorage.app',
    measurementId: 'G-6YDNZZ03VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2AxOKm-h_H5G0CW3_ItTr6f-FR5WEz2c',
    appId: '1:378281753444:android:915c5af0774b1e4d819871',
    messagingSenderId: '378281753444',
    projectId: 'automacao-5843f',
    storageBucket: 'automacao-5843f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqaVVMaWA8jQT2zsetVxuwfRkm0m2jUOo',
    appId: '1:378281753444:ios:71c4c261e6e42e67819871',
    messagingSenderId: '378281753444',
    projectId: 'automacao-5843f',
    storageBucket: 'automacao-5843f.firebasestorage.app',
    iosBundleId: 'com.example.automacao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqaVVMaWA8jQT2zsetVxuwfRkm0m2jUOo',
    appId: '1:378281753444:ios:71c4c261e6e42e67819871',
    messagingSenderId: '378281753444',
    projectId: 'automacao-5843f',
    storageBucket: 'automacao-5843f.firebasestorage.app',
    iosBundleId: 'com.example.automacao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB14spd0k5x_4m6zZYWJAZLqBnI6jeZyBc',
    appId: '1:378281753444:web:fdf6ef936fdbc6f0819871',
    messagingSenderId: '378281753444',
    projectId: 'automacao-5843f',
    authDomain: 'automacao-5843f.firebaseapp.com',
    storageBucket: 'automacao-5843f.firebasestorage.app',
    measurementId: 'G-YCE0KF1442',
  );
}
